### ISSUE TITLE
Website redirect issue

### ISSUE THREAD

**Issue by plunginghornets** [ChrisLane/open-sudoku#1]
http://opensudoku.moire.org/

This is the page that is linked when you click "Get more puzzled online", but it currently goes to a "page isn't redirecting properly" error.

Love Open Sudoku and use it almost daily. Ive tried finding somewhere else to get puzzles but they are all just printable puzzles. Hope this is an easy fix and not a loss of support.

**Comment by ChrisLane** [comment]
This is only a fork of the old repository for Open Sudoku.
Please create your issue at https://gitlab.com/opensudoku/opensudoku
